---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { .Values.name } }
  namespace: { { .Values.namespace } }
  labels:
    app: { { .Values.name } }

spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { .Values.name } }
  template:
    metadata:
      labels:
        app: { { .Values.name } }
    spec:
      containers:
        - name: { { .Values.name } }
          resources: { { toYaml .Values.resources | nindent 10 } }
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
